-- DO NOT EDIT THIS FILE (synced by HIT)
-- Source: hit-feature-pack-tasks-admin/migrations/001_create_task_runtime_tables.sql
-- Feature Pack: tasks-admin

-- Minimal task runtime tables (app-owned, no K8s/CAC dependencies)
--
-- These tables are intentionally simple and Postgres-first.
-- If/when we need chunked logs, we can add a separate logs table.

create table if not exists hit_task_schedules (
  task_name text primary key,
  schedule_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists hit_task_executions (
  id uuid primary key default gen_random_uuid(),
  task_name text not null,
  service_name text,
  triggered_by text,
  status text not null default 'queued', -- queued | running | success | failed
  enqueued_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  exit_code integer,
  duration_ms integer,
  error text,
  logs text not null default ''
);

create index if not exists hit_task_executions_task_name_idx
  on hit_task_executions (task_name);

create index if not exists hit_task_executions_status_idx
  on hit_task_executions (status);

create index if not exists hit_task_executions_enqueued_at_idx
  on hit_task_executions (enqueued_at desc);

